version: '3'
services:

    etcd:
        image: quay.io/coreos/etcd:v3.2.5
        restart: always
        ports:
             - 2379:2379
             - 2380:2380
        volumes:
          - etcd-data:/etcd-data
        environment:
            ETCD_NAME: node1
            ETCD_DATA_DIR: /etcd-data
            ETCDCTL_API: 3
            ETCD_DEBUG: 1
            ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380 --listen-peer-urls http://0.0.0.0:2380
            ETCD_INITIAL_CLUSTER: node1=http://0.0.0.0:2380
            ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379

volumes:
  etcd-data:
