version: '2'

vars:
  Dir:
    sh: basename "$PWD"

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Run the glorious app.
    cmds:
      - task: build
      - ./bin/{{.Dir}}{{exeExt}}

  clean:
    desc: Cleanup the build artifacts.
    cmds:
      - echo "Cleaning ..."
      - rm -rf bin/ *.html *.out | exit 0;

  install:
    desc: Install all dependencies.
    cmds:
      - echo "Installing Dependencies ..."
      - go get -u github.com/tcnksm/ghr
      - go get -u github.com/mitchellh/gox
      - go get -u github.com/golang/dep/cmd/dep
      - go get -u github.com/alecthomas/gometalinter
      - go get -u github.com/kisielk/errcheck
      - go get -u github.com/golang/protobuf/protoc-gen-go
      - go get -u github.com/fiorix/protoc-gen-cobra
      - go get -u github.com/gogo/protobuf/protoc-gen-gofast

  gen-proto:
    desc: Generate protobuf client/server & cmd
    cmds:
      - mkdir -p bin/gen
      - mkdir -p bin/cli
      - protoc --gofast_out=plugins=grpc:./proto --cobra_out=plugins=client:./bin/cli --proto_path=proto --cobra_out=bin/cli proto/*.proto

  test:
    desc: Run all the go tests.
    cmds:
      - go test -v -race ./...

  cov:
    desc: Generate test converage.
    cmds:
      - go test -v -cover -coverprofile=c.out
      - go tool cover -html=c.out -o coverage.html

  vet:
    desc: Reports suspicious code.
    cmds:
      - go vet ./...

  lint:
    desc: Run all the linters.
    cmds:
      - gometalinter --disable-all --enable=errcheck --enable=vet --enable=vetshadow ./...

  ci:
    desc: Run it like Volkswagen.
    cmds:
      - task: test
      - task: lint

  build:agent:
    desc: Run all the go tests.
    sources:
      - ./agent/*.go
    generates:
      - bin/*.{{exeExt}}
    cmds:
      - echo "Building ({{.Dir}}) ..."
      - mkdir -p bin
      - gox -output {{printf "bin/{{.Dir}}_{{.OS}}_{{.Arch}}"}} -os="linux" -os="darwin" -arch="386" -arch="amd64" ./agent

  build:server:
    desc: Run all the go tests.
    sources:
      - ./server/*.go
    generates:
      - bin/*.{{exeExt}}
    cmds:
      - echo "Building ({{.Dir}}) ..."
      - mkdir -p bin
      - gox -output {{printf "bin/{{.Dir}}_{{.OS}}_{{.Arch}}"}} -os="linux" -os="darwin" -arch="386" -arch="amd64" ./server

  docker:
    desc: Build docker.
    deps: [release]
    cmds:
      - docker build --build-arg BIN={{.Dir}} -t {{.Dir}}:latest .

  release:
    desc: Release the glorious app.
    deps: [clean, test, lint, cov]
    generates:
      - bin/*.{{exeExt}}
    cmds:
      - task: build
