// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	// Types that are valid to be assigned to Event:
	//	*Event_Reserve
	Event                isEvent_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Reserve struct {
	Reserve *Reserve `protobuf:"bytes,1,opt,name=reserve,proto3,oneof"`
}

func (*Event_Reserve) isEvent_Event() {}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Event) GetReserve() *Reserve {
	if x, ok := m.GetEvent().(*Event_Reserve); ok {
		return x.Reserve
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Event) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Event_Reserve)(nil),
	}
}

type Reserve struct {
	Memory               uint64   `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reserve) Reset()         { *m = Reserve{} }
func (m *Reserve) String() string { return proto.CompactTextString(m) }
func (*Reserve) ProtoMessage()    {}
func (*Reserve) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{1}
}

func (m *Reserve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reserve.Unmarshal(m, b)
}
func (m *Reserve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reserve.Marshal(b, m, deterministic)
}
func (m *Reserve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reserve.Merge(m, src)
}
func (m *Reserve) XXX_Size() int {
	return xxx_messageInfo_Reserve.Size(m)
}
func (m *Reserve) XXX_DiscardUnknown() {
	xxx_messageInfo_Reserve.DiscardUnknown(m)
}

var xxx_messageInfo_Reserve proto.InternalMessageInfo

func (m *Reserve) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

// Cluster is representing a set of agents with resources
//
// A cluster is a logical collection of agents.
type Cluster struct {
	// The unique identifier of a cluster.
	// It has to be unique to cluster resources accordingly,
	// and transport offers and ACKs.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The canonical name of a cluster.
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{2}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Agent is representing an agent to scheduler
//
// This is the identification of an agent to the scheduler.
// It contains all the information about an agent.
type Agent struct {
	// Unique id of the agent.
	// Which is either generated or provided.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// A canonical name for the agent.
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{3}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Request message for RegisterAgent
type RegisterAgentRequest struct {
	// The agent which wants to register.
	Agent                *Agent   `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAgentRequest) Reset()         { *m = RegisterAgentRequest{} }
func (m *RegisterAgentRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterAgentRequest) ProtoMessage()    {}
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{4}
}

func (m *RegisterAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAgentRequest.Unmarshal(m, b)
}
func (m *RegisterAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAgentRequest.Marshal(b, m, deterministic)
}
func (m *RegisterAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAgentRequest.Merge(m, src)
}
func (m *RegisterAgentRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterAgentRequest.Size(m)
}
func (m *RegisterAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAgentRequest proto.InternalMessageInfo

func (m *RegisterAgentRequest) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Response message for RegisterAgent
type RegisterAgentResponse struct {
	// The cluster the agent is register to.
	Cluster              *Cluster `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterAgentResponse) Reset()         { *m = RegisterAgentResponse{} }
func (m *RegisterAgentResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterAgentResponse) ProtoMessage()    {}
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ed94b0a22d11796, []int{5}
}

func (m *RegisterAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterAgentResponse.Unmarshal(m, b)
}
func (m *RegisterAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterAgentResponse.Marshal(b, m, deterministic)
}
func (m *RegisterAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterAgentResponse.Merge(m, src)
}
func (m *RegisterAgentResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterAgentResponse.Size(m)
}
func (m *RegisterAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterAgentResponse proto.InternalMessageInfo

func (m *RegisterAgentResponse) GetCluster() *Cluster {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Reserve)(nil), "proto.Reserve")
	proto.RegisterType((*Cluster)(nil), "proto.Cluster")
	proto.RegisterType((*Agent)(nil), "proto.Agent")
	proto.RegisterType((*RegisterAgentRequest)(nil), "proto.RegisterAgentRequest")
	proto.RegisterType((*RegisterAgentResponse)(nil), "proto.RegisterAgentResponse")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_7ed94b0a22d11796) }

var fileDescriptor_7ed94b0a22d11796 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0x3b, 0x4b, 0x03, 0x41,
	0x10, 0x36, 0x92, 0xcd, 0xe2, 0xe7, 0xa3, 0x18, 0x54, 0x82, 0x5a, 0xe8, 0x56, 0xc1, 0x22, 0x62,
	0xec, 0xc4, 0x26, 0x8a, 0x20, 0x96, 0x0b, 0xda, 0x9f, 0x66, 0x88, 0x87, 0xde, 0x6d, 0xdc, 0x47,
	0xc0, 0x7f, 0x2f, 0xfb, 0x88, 0xe0, 0x69, 0x91, 0xea, 0x66, 0xbe, 0xc7, 0xed, 0xf7, 0x0d, 0xd0,
	0x54, 0x75, 0x3b, 0x5e, 0x58, 0xe3, 0x0d, 0x89, 0xf4, 0x51, 0x37, 0x10, 0xf7, 0x4b, 0x6e, 0x3d,
	0x9d, 0x43, 0x5a, 0x76, 0x6c, 0x97, 0x3c, 0xec, 0x9d, 0xf6, 0x46, 0xdb, 0x93, 0xbd, 0x2c, 0x1c,
	0xeb, 0x8c, 0x3e, 0x6c, 0xe8, 0x95, 0xe0, 0x56, 0x42, 0x70, 0x34, 0xa9, 0x33, 0xc8, 0x42, 0xd3,
	0x21, 0x06, 0x0d, 0x37, 0xc6, 0x7e, 0x25, 0x7b, 0x5f, 0x97, 0x4d, 0x5d, 0x42, 0xde, 0x7d, 0x04,
	0xe7, 0xd9, 0x12, 0xa1, 0x1f, 0x42, 0x3d, 0x4b, 0x82, 0x2d, 0x9d, 0xe6, 0x88, 0xb5, 0x55, 0xc3,
	0xc3, 0xcd, 0x8c, 0xc5, 0x59, 0x5d, 0x40, 0x4c, 0xe7, 0x31, 0xd3, 0xba, 0x86, 0x6b, 0xec, 0x6b,
	0x9e, 0xd7, 0xf1, 0x91, 0x64, 0xd4, 0xfc, 0x19, 0xd8, 0x79, 0x52, 0x10, 0x55, 0xdc, 0x4b, 0xa3,
	0x9d, 0xd2, 0x28, 0x6b, 0x32, 0xa5, 0xa6, 0x38, 0xe8, 0x78, 0xdd, 0xc2, 0xb4, 0x8e, 0x69, 0x04,
	0xf9, 0x9a, 0x83, 0x77, 0x0e, 0x52, 0xea, 0xe8, 0x15, 0x3d, 0x79, 0x82, 0x7c, 0x36, 0xee, 0xfd,
	0xcd, 0xcc, 0xe8, 0x11, 0xbb, 0xbf, 0xfe, 0x46, 0xc7, 0x3f, 0x57, 0xfc, 0x9b, 0xef, 0xe8, 0xe4,
	0x7f, 0x32, 0x07, 0x78, 0x19, 0x24, 0xf2, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x12, 0x29, 0x18,
	0x0c, 0xb6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VoskhodClient is the client API for Voskhod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VoskhodClient interface {
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
}

type voskhodClient struct {
	cc *grpc.ClientConn
}

func NewVoskhodClient(cc *grpc.ClientConn) VoskhodClient {
	return &voskhodClient{cc}
}

func (c *voskhodClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, "/proto.Voskhod/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoskhodServer is the server API for Voskhod service.
type VoskhodServer interface {
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
}

func RegisterVoskhodServer(s *grpc.Server, srv VoskhodServer) {
	s.RegisterService(&_Voskhod_serviceDesc, srv)
}

func _Voskhod_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoskhodServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Voskhod/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoskhodServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Voskhod_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Voskhod",
	HandlerType: (*VoskhodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _Voskhod_RegisterAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
